spring:
 application:
  name: inv-master-db-api
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/inventory
  username: postgres
  password: postgres
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
  properties:
   hibernate:
    temp:
     use_jdbc_metadata_defaults: false
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  
server:
 port: 8002
 servlet:
  contextPath: /inv-master